# Generated by Django 3.2.4 on 2021-06-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Date',
            new_name='date',
        ),
    ]
